//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmohasebDA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmohasebSQLEntities : DbContext
    {
        public AlmohasebSQLEntities()
            : base("name=AlmohasebSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<The_Barcode> The_Barcode { get; set; }
        public virtual DbSet<The_ItemDetails> The_ItemDetails { get; set; }
        public virtual DbSet<The_Items> The_Items { get; set; }
        public virtual DbSet<The_Permissions> The_Permissions { get; set; }
    }
}
