//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmohasebDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class The_ItemDetails
    {
        public int ItemDetails_No { get; set; }
        public Nullable<int> Item_No { get; set; }
        public Nullable<float> Item_Quantity { get; set; }
        public Nullable<float> Item_Reserved { get; set; }
        public Nullable<decimal> Item_Cost { get; set; }
        public Nullable<int> PlaceExchange_No { get; set; }
        public Nullable<int> PlaceOffer_No { get; set; }
        public Nullable<System.DateTime> Last_Movement { get; set; }
        public Nullable<System.DateTime> Exp_date { get; set; }
        public Nullable<System.DateTime> Item_Add { get; set; }
        public string LocalHostName { get; set; }
        public string NewItem_Add { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual The_Items The_Items { get; set; }
    }
}
