//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmohasebDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class The_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public The_Items()
        {
            this.The_Barcode = new HashSet<The_Barcode>();
            this.The_ItemDetails = new HashSet<The_ItemDetails>();
        }
    
        public int Item_No { get; set; }
        public string Scientific_Name { get; set; }
        public Nullable<float> Out_quantitative { get; set; }
        public bool Type_validity { get; set; }
        public Nullable<float> Redial { get; set; }
        public bool Item_Status { get; set; }
        public Nullable<short> Item_kind { get; set; }
        public Nullable<int> FormPackaging_No { get; set; }
        public Nullable<int> Group_No { get; set; }
        public Nullable<System.DateTime> Last_Movement { get; set; }
        public Nullable<System.DateTime> Item_Add { get; set; }
        public string LocalHostName { get; set; }
        public bool Item_Sn { get; set; }
        public bool Bar_Print { get; set; }
        public Nullable<int> Person_No { get; set; }
        public string NewItem_Add { get; set; }
        public bool Show_menu { get; set; }
        public bool Quntity_Rounded { get; set; }
        public Nullable<float> Old_Unit { get; set; }
        public Nullable<float> Nesba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<The_Barcode> The_Barcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<The_ItemDetails> The_ItemDetails { get; set; }
    }
}
