//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmohasebDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class The_Barcode
    {
        public int Bar_No { get; set; }
        public Nullable<int> Item_No { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Unit_No { get; set; }
    
        public virtual The_Items The_Items { get; set; }
    }
}
