//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmohasebDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class The_Permissions
    {
        public int Permissions_No { get; set; }
        public Nullable<int> Person_No { get; set; }
        public bool See_Price { get; set; }
        public bool Change_Users { get; set; }
        public bool Change_Settings { get; set; }
        public bool Modify_Payment { get; set; }
        public bool Registration_Expenses { get; set; }
        public bool Showing_Income { get; set; }
        public bool Returns { get; set; }
        public bool Show_Profit { get; set; }
        public bool Price_Adjustment { get; set; }
        public bool Storage_Display { get; set; }
        public Nullable<bool> Sales_List { get; set; }
        public Nullable<bool> Free { get; set; }
        public Nullable<bool> Free1 { get; set; }
        public Nullable<bool> Free2 { get; set; }
    }
}
